### ISSUE TITLE
Como alumno necesito ver el listado de asignaturas para poder seleccionar una

### ISSUE THREAD

**Issue by AdrianArnaiz** [RodrigoBarandaCastrillo/PrimerRepositorio#2]
Vamos a tener en cuenta blablabla
Antes necesito resolver #1 
@RodrigoBarandaCastrillo es el compa del project.
- [ ] Hacer a.

- [ ] Hacer b.

**Comment by AdrianArnaiz** [comment]
#1

**Comment by RubenMartinezAragon** [comment]
wapo artack
